added example of flashing from python code (ESPTOOL-952)
espressif/esptool pull request #1029
Opened 2024-10-29 19:09 UTC by brentpicasso

Example app demonstrating how to flash from python code.  Follow up from PR #1022

2024-11-03 22:50 UTC, radimkarnis commented
Hi @brentpicasso,
thanks for taking the time to follow up and contribute to the documentation!

We will be refactoring esptool to be easily usable as a Python module in the next major release, so this script will most likely stop working quite soon due to changing APIs. On the other hand, starting with the documentation now won't hurt; this contribution seems like a good start.

I have some issues and suggestions before we can move on. Feel free to say you don't have time for this, in that case, I can take over.

2024-11-03 22:51 UTC, radimkarnis commented
1) The commit name, please see the message from our bot above this comment. The commit type is missing. I suggest something like `docs(scripting): Add example of usage as a Python module".

2024-11-03 22:51 UTC, radimkarnis commented
2) New docs page. We already have a page explaining some basic scripting [here](https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/scripting.html). I would add this as a new section (e.g. `Using Esptool as a Python Module`).

2024-11-03 23:00 UTC, radimkarnis requested changes
Left a few suggestions. Let me know if that seems reasonable!

2024-11-03 23:00 UTC, radimkarnis commented on docs/en/advanced-topics/flashing-from-python-code.rst
> +The following is an example on how to flash the ESP32 from a custom application:
Changing `ESP32` to `{IDF_TARGET_NAME}` will make it dynamically change based on the selected target.

2024-11-03 23:00 UTC, radimkarnis commented on docs/en/advanced-topics/flashing-from-python-code.rst
> +#beginning of flash address
Please keep all the comments formatted uniformly.

2024-11-03 23:00 UTC, radimkarnis commented on docs/en/advanced-topics/flashing-from-python-code.rst
> +        block_size = BLOCK_SIZE
This is called `FLASH_WRITE_SIZE` in esptool and changes depending on if that's the ROM bootloader or the stub. 
So in this case `block_size = stub.FLASH_WRITE_SIZE` seems better.

2024-11-03 23:00 UTC, radimkarnis commented on docs/en/advanced-topics/flashing-from-python-code.rst
> +FLASH_BEGIN = 0x10000
Suggest renaming to `FLASH_ADDRESS` or `FLASH_OFFSET`

2024-11-11 00:19 UTC, brentpicasso commented
Hi, @radimkarnis I ran out of time this week, preparing for some travel.  I accept your offer to move it forward! Thank you!

2024-11-29 12:03 UTC, closed without merging