feat(esptool): allow filtering ports by VID/PID
espressif/esptool pull request #988
Opened 2024-07-01 20:29 UTC by bryghtlabs-richard

Enables user to specify --usbVid and/or --usbPid, which filter the com port list before checking for ESP chips. With many serial ports on the computer, this greatly speeds up the process of esptool identifying the correct com port by allowing esptool to skip all com ports without a matching VID/PID. Implements https://github.com/espressif/esptool/issues/987

# I have tested this change with the following hardware & software combinations:

NO TESTING ON MAC/LINUX. Tested on Windows64 with ESP32-S3-DevKitC and custom ESP32-S3 board.

```
$ time esptool read_flash_status
esptool.py v4.7.0
Found 4 serial ports
Serial port COM30
Connecting......................................
COM30 failed to connect: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
Serial port COM29
Connecting......................................
COM29 failed to connect: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
Serial port COM18
Connecting...
Detecting chip type... ESP32-S3
...long text omitted...
real    0m18.193s
user    0m0.000s
sys     0m0.015s
```

```
$ time esptool --usbVid 0x303a read_flash_status
esptool.py v4.7.0
Found 1 serial ports
Serial port COM18
Connecting...
Detecting chip type... ESP32-S3
...long text omitted...
real    0m1.067s
user    0m0.000s
sys     0m0.000s
```

# I have run the esptool.py automated integration tests with this change and the above hardware:

$ pytest test_esptool.py --port COM49 --chip esp32s3 --baud 230400
============================= test session starts =============================
platform win32 -- Python 3.11.5, pytest-8.2.2, pluggy-1.5.0
rootdir: C:\Projects\esptool
configfile: pyproject.toml
collected 88 items

test_esptool.py sss.......ss.................s.s.........s....sss.s..... [ 63%]
......s...sssssss..ssss..s..ssss                                         [100%]

============================== warnings summary ===============================
test_esptool.py:120
  C:\Projects\esptool\test\test_esptool.py:120: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.flaky(reruns=1, condition=arg_preload_port is not False)

test_esptool.py:1204
  C:\Projects\esptool\test\test_esptool.py:1204: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.flaky(reruns=5)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========== 59 passed, 29 skipped, 2 warnings in 415.91s (0:06:55) ============

2024-07-04 12:35 UTC, dobairoland commented
Thank you for the contribution. I think this is a good idea but we might think about a little what new CLI arguments we add. I'm worried that others might need other type of filtering (e.g. serial_number, location) for which we would have to add also new arguments. 

- This is one solution to merge the arguments: `--port-filter <vid>:<pid>` where `<vid>` and `<pid>` could be `*` as well. 
- An even more general solution: `--port-filter vid=<number> --port-filter pid=<number>` where `--port-filter` can be repeated several times and can be easily extended.

What do you think @radimkarnis, @peterdragun?

2024-07-08 10:44 UTC, peterdragun commented
Overall I like the idea, but as mentioned I would go with one argument for both options.
Maybe we can extend the filter to also cover the port name? For example on macOS ports can have different names based on whether they are using a USB to UART bridge (`/dev/cu.usbserial-XX`) or USB Serial/JTAG (`/dev/cu.usbmodemXX`). So in case I know which peripheral I want to use but don't know the number it may be helpful. I mean we can do that based on VID as well, but it would be easier to remember the port name than VID.

2024-07-08 12:32 UTC, dobairoland commented
> Overall I like the idea, but as mentioned I would go with one argument for both options. Maybe we can extend the filter to also cover the port name? For example on macOS ports can have different names based on whether they are using a USB to UART bridge (`/dev/cu.usbserial-XX`) or USB Serial/JTAG (`/dev/cu.usbmodemXX`). So in case I know which peripheral I want to use but don't know the number it may be helpful. I mean we can do that based on VID as well, but it would be easier to remember the port name than VID.

I think this could be covered by the following if we go with my second proposal:
```
--port-filter name=usbserial
```

2024-07-08 15:35 UTC, bryghtlabs-richard commented
> An even more general solution: --port-filter vid=<number> --port-filter pid=<number> where --port-filter can be repeated several times and can be easily extended.

I like this.

> I think this could be covered by the following if we go with my second proposal: `--port-filter name=usbserial`

Are you thinking a substring search, or should we check against a prefix from the pyserial port name, like `name=/dev/cu.usbserial`?

2024-07-08 16:49 UTC, dobairoland commented
> Are you thinking a substring search, or should we check against a prefix from the pyserial port name, like name=/dev/cu.usbserial?

Substring search is what I had in my mind. `ttyUSB` and `ttyACM` could be easily used on Linux, or even simply `USB` or `ACM`. But this was just a suggestion so we don't end up needing several similar arguments. You don't have to address this in this PR (if you don't want).

On the other hand, what would be great to update in this PR is the documentation and mention this new feature somewhere. Perhaps in a separate section in https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/advanced-options.html.

2024-07-22 07:14 UTC, dobairoland commented
Hi @bryghtlabs-richard. Could you please get back to this pull request and finish it as we've discussed?

2024-07-29 16:43 UTC, bryghtlabs-richard commented
Hi @dobairoland , I'm back from a vacation and I think I've got everything we want, and updated the documentation.

2024-07-30 13:17 UTC, dobairoland requested changes
Thanks. This looks pretty good. I've left a couple of last suggestions.

2024-07-30 13:17 UTC, dobairoland commented on docs/en/esptool/advanced-options.rst
> +with many serial ports There are a few different types that can be combined. A port must match all specified FilterTypes, and must match
"ports There" -> "ports. There"

2024-07-30 13:17 UTC, dobairoland commented on esptool/__init__.py
> +        if names and (port.name is None or not substr_in_list(port.name, names)):
This substr_in_list is very specific and with inverting the result it is pretty hard to understand.  Could we replace it with an inline check similar to the following?

```python
... or any(name not in port.name for name in names)
```

2024-07-30 13:17 UTC, dobairoland commented on esptool/__init__.py
> +        help="Serial port device filter, can be vid=INT, pid=INT, name=SUBSTRING",
(optional) I think NUMBER instead of INT would be clearer for users.

2024-07-30 13:31 UTC, bryghtlabs-richard commented
Thanks Roland, I've updated the commit with your suggestions.

2024-07-30 13:48 UTC, dobairoland commented on esptool/__init__.py
> +        if names and (port.name is None or not substr_in_list(port.name, names)):
And I see I've made a mistake. You corrected it to `not any()`. That could be `all()` instead. You can ignore this if you won't make any more changes to this PR.

2024-07-30 14:07 UTC, radimkarnis commented on docs/en/esptool/advanced-options.rst
> +    * ``--port-filter vid=0x303A --port-filter pid=0x1001`` matches Espressif ESP32-S3 ports by VID and PID.
`303A`:`1001` is not actually just the  ESP32-S3, but the USB-Serial/JTAG unit in general. That means any chip with this peripheral will show up with this VID:PID (S3, C3, C6, H2, P4, ...). 

If you want to mention a specific chip, USB-OTG mode has to be used. e.g. `ESP32-S2` = `VID:PID=303A:0002`

2024-07-30 14:14 UTC, radimkarnis commented
Suggestion: A nice touch would be to add a mention about the Espressif USB customer-allocated PID repository
https://github.com/espressif/usb-pids. Essentially we allow users to register a PID under the Espressif VID for a specific piece of hardware. So one of the examples could maybe mention this?

Feel free to ignore, though!

2024-07-30 14:57 UTC, Jason2866 commented
Agree, nice feature!

2024-08-01 11:21 UTC, merged

2024-08-01 11:28 UTC, dobairoland commented
@bryghtlabs-richard Thank you for the contribution. It was merged.